### ISSUE TITLE
how install ngx spped with last nginx  nginx/1.11.5

### ISSUE THREAD

**Issue by twins16** [apache/incubator-pagespeed-ngx#1299]
how install ngx spped with last nginx  nginx/1.11.5 
thank you

**Comment by oschaaf** [comment]
Do you run into a specific problem with nginx 1.11.5? 
Did you try the guide here?: https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source

**Comment by twins16** [comment]
not working at all i install it lot of times but now i don't ander stand what hapend 
thank's i will see on google thank's

**Comment by oschaaf** [comment]
@twins16 have you been able to get ngx_pagespeed up and running? Can we close this?

**Comment by kanamania** [comment]
It'll be great if you can put the version of pagespeed on the README and on it's site. Right I want to build it on my centos 7.2 droplet but I can seem to find the version of the master zipball I downloaded here.

**Comment by shirokoweb** [comment]
I think @twins16 tried to install nginx with ngx_pagespeed module following the "Automated Install".
The title is a bit disturbing, because it is not really an "Automated Install" as a apt install nginx would be.
In fact, it only compiles both sources (which is a great improvement btw), on the other hand, you need to configure and created all files / folders, such as NGINX systemd service file to be able to start nginx server or /sites-available/ /sites-enabled/ foldder and so on.

**Comment by arielesp** [comment]
latest pagespeed only is working with nginx until 1.13.3 .... 
I already tried 1.13.4 and 1.13.5 ... dont install...

**Comment by oschaaf** [comment]
@arielesp see https://github.com/pagespeed/ngx_pagespeed/issues/1472
