### ISSUE TITLE
[Solved] Pagespeed increases page size with no filters?

### ISSUE THREAD

**Issue by Graymanflo** [apache/incubator-pagespeed-ngx#1584]
Good afternoon!

I am trying to use pagespeed with latest Nginx build (1.15.2), although as it turns out when I enable pagespeed the pagesize increases significantly to 32kb from 9kb with no filters:

**nginx.conf**
> pagespeed on;
> pagespeed RewriteLevel PassThrough;
> pagespeed FileCachePath /var/ngx_pagespeed_cache;

Results with pagespeed **enabled**:
![pagespeed on;](https://i.imgur.com/3XPvb88.png)

Results with pagespeed **disabled**:
![pagespeed off;](https://i.imgur.com/ezNfJX6.png)

I disable cache in both tests and each time I get identical results, why is this happening?

**Comment by jmarantz** [comment]
Not sure -- can you click on 'index.php' in the waterfall and check whether they differ due to gzip encoding?

After that, the next thing I'd check for is to compare the HTML itself and see if PageSpeed is adding something. It's possible there's some inherited configuration from a higher scope, enabling a filter that requires some injected inline javascript, e.g. above-the-fold detection for inline images.

**Comment by Graymanflo** [comment]
You are completely right, I compared the content of the index.html but both were identical, however I accidentally left gzip variables in my nginx.conf with `gzip off;`, pagespeed decided to still use gzip, thanks works good now.
