### ISSUE TITLE
document good origin HTTP header settings / nginx config / etags / nginx pagespeed output headers

### ISSUE THREAD

**Issue by adrelanos** [apache/incubator-pagespeed-ngx#1694]
What are some good combinations of HTTP headers? What should users of pagespeed check their webapps are outputting wrt HTTP headers? Are there some good examples of recommended origin caching HTTP headers? Perhaps there are multiple valid combinations? Or good websites that have good caching settings which are a good role model?

Could you please provide a basic nginx config for static contents? There's a lot. Expires; HTTP ETag; weak ETag; vs gzip; last modified. It's still unclear the me which combination of settings / HTTP headers are a good basis for pagespeed to work with.

Pagespeed showing an `Etag: W/"0"` being for cachable static files is expected or a bug?

**Comment by Lofesa** [comment]
Pagespeed don´t care about what headers are you using, the only thing that matters is public cacheability. Whe a resource is optimized, then pagespeed put 1 year for ttl.
The html himself is served whit cache-control header with max-age=0, so is not stored in any cache.
The etag:W/"0" is the expected behaviour. The W is a weak validator, resource are semanticaly the same, but not byte by byte. [(doc)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)
